// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: demo.proto
#ifndef GRPC_demo_2eproto__INCLUDED
#define GRPC_demo_2eproto__INCLUDED

#include "demo.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ZYF {

class YServer final {
 public:
  static constexpr char const* service_full_name() {
    return "ZYF.YServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::ZYF::Res* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ZYF::Res>> AsyncGetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ZYF::Res>>(AsyncGetNumRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ZYF::Res>> PrepareAsyncGetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ZYF::Res>>(PrepareAsyncGetNumRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetNum(::grpc::ClientContext* context, const ::ZYF::Num* request, ::ZYF::Res* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNum(::grpc::ClientContext* context, const ::ZYF::Num* request, ::ZYF::Res* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ZYF::Res>* AsyncGetNumRaw(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ZYF::Res>* PrepareAsyncGetNumRaw(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::ZYF::Res* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ZYF::Res>> AsyncGetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ZYF::Res>>(AsyncGetNumRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ZYF::Res>> PrepareAsyncGetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ZYF::Res>>(PrepareAsyncGetNumRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetNum(::grpc::ClientContext* context, const ::ZYF::Num* request, ::ZYF::Res* response, std::function<void(::grpc::Status)>) override;
      void GetNum(::grpc::ClientContext* context, const ::ZYF::Num* request, ::ZYF::Res* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ZYF::Res>* AsyncGetNumRaw(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ZYF::Res>* PrepareAsyncGetNumRaw(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetNum_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetNum(::grpc::ServerContext* context, const ::ZYF::Num* request, ::ZYF::Res* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNum() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNum(::grpc::ServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNum(::grpc::ServerContext* context, ::ZYF::Num* request, ::grpc::ServerAsyncResponseWriter< ::ZYF::Res>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetNum<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNum() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ZYF::Num, ::ZYF::Res>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ZYF::Num* request, ::ZYF::Res* response) { return this->GetNum(context, request, response); }));}
    void SetMessageAllocatorFor_GetNum(
        ::grpc::MessageAllocator< ::ZYF::Num, ::ZYF::Res>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ZYF::Num, ::ZYF::Res>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNum(::grpc::ServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNum(
      ::grpc::CallbackServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetNum<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNum() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNum(::grpc::ServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNum() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNum(::grpc::ServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNum(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNum() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNum(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNum(::grpc::ServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNum(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNum : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNum() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ZYF::Num, ::ZYF::Res>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ZYF::Num, ::ZYF::Res>* streamer) {
                       return this->StreamedGetNum(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNum() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNum(::grpc::ServerContext* /*context*/, const ::ZYF::Num* /*request*/, ::ZYF::Res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNum(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ZYF::Num,::ZYF::Res>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetNum<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetNum<Service > StreamedService;
};

}  // namespace ZYF


#endif  // GRPC_demo_2eproto__INCLUDED
