// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: demo.proto

#include "demo.pb.h"
#include "demo.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ZYF {

static const char* YServer_method_names[] = {
  "/ZYF.YServer/GetNum",
};

std::unique_ptr< YServer::Stub> YServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< YServer::Stub> stub(new YServer::Stub(channel, options));
  return stub;
}

YServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetNum_(YServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status YServer::Stub::GetNum(::grpc::ClientContext* context, const ::ZYF::Num& request, ::ZYF::Res* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ZYF::Num, ::ZYF::Res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNum_, context, request, response);
}

void YServer::Stub::async::GetNum(::grpc::ClientContext* context, const ::ZYF::Num* request, ::ZYF::Res* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ZYF::Num, ::ZYF::Res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNum_, context, request, response, std::move(f));
}

void YServer::Stub::async::GetNum(::grpc::ClientContext* context, const ::ZYF::Num* request, ::ZYF::Res* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ZYF::Res>* YServer::Stub::PrepareAsyncGetNumRaw(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ZYF::Res, ::ZYF::Num, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ZYF::Res>* YServer::Stub::AsyncGetNumRaw(::grpc::ClientContext* context, const ::ZYF::Num& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNumRaw(context, request, cq);
  result->StartCall();
  return result;
}

YServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      YServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< YServer::Service, ::ZYF::Num, ::ZYF::Res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](YServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ZYF::Num* req,
             ::ZYF::Res* resp) {
               return service->GetNum(ctx, req, resp);
             }, this)));
}

YServer::Service::~Service() {
}

::grpc::Status YServer::Service::GetNum(::grpc::ServerContext* context, const ::ZYF::Num* request, ::ZYF::Res* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ZYF

